---

- name: "Create primary group {{ groupname }}"
  ansible.builtin.group:
    name: "{{ groupname }}"
    state: present

- name: "Create additional groups {{ user_groups }}"
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ user_groups }}"
  when: user_groups is defined

- name: "Create user account for {{ user_item }}"
  ansible.builtin.user:
    name: "{{ user_item }}"
    group: "{{ groupname }}"

- name: "Put users in groups {{ user_groups }}"
  ansible.builtin.user:
    name: "{{ user_item }}"
    groups: "{{ user_groups }}"
    append: yes
  when: user_groups is defined

- name: "Set shell for user {{ user_item }}"
  ansible.builtin.user:
    name: "{{ user_item }}"
    shell: "{{ user_shell }}"
  when: user_shell is defined

- name: "Create directory ssh directory for user {{ user_item }}"
  ansible.builtin.file:
    path: "/home/{{ user_item }}/.ssh"
    state: directory
    owner: "{{ user_item }}"
    group: "{{ groupname }}"
    mode: 0700

- name: "Install authorized_keys file for user {{ user_item }}"
  ansible.builtin.copy:
    src: "ssh/{{ user_item }}.pub"
    dest: "/home/{{ user_item }}/.ssh/authorized_keys"
    owner: "{{ user_item }}"
    group: "{{ groupname }}"
    mode: 0644
