---

- name: "Create user group {{ item }}"
  ansible.builtin.group: name={{ item }} state=present
- name: "Create user account for {{ item }}"
  ansible.builtin.user: name={{ item }} group={{ item }}
- name: "Set shell for user {{ item }}"
  ansible.builtin.user: name={{ item }} shell={{ user_shell }}
  when: user_shell is defined
- name: "Create directory ssh directory for user {{ item }}"
  ansible.builtin.file: path=/home/{{ item }}/.ssh state=directory owner={{ item }} group={{ item }} mode=0700
