---
# Syntax:
#
# Roles:
# - { role: user, users: [ 'username1', 'username2' ], groupname: mygroup, admin: true }
#
# To use this role in a 'bootstraping' playbook use this syntax:
#
# - include_role:
#     name: user
#   vars:
#     users: [ 'username1', 'username2' ]
#     groupname: mygroup
#     admin: true
#
# The usernames are given by a list and the groupname is set. The variable
# 'admin' defines if the group has sudoers rights.
#

- include_tasks: create_user.yml
  with_items: "{{ users }}"
- import_tasks: create_group.yml
  when: groupname is defined
- import_tasks: install_authorized_keys.yml
- import_tasks: create_sudoers.yml
