---
# Syntax:
#
# Roles:
# - { role: user, users: [ 'username1', 'username2' ], groupname: mygroup, admin: true }
#
# To use this role in a 'bootstraping' playbook use this syntax:
#
# - include_role:
#     name: user
#   vars:
#     users: [ 'username1', 'username2' ]
#     groupname: mygroup
#     groups: [ 'mygroup1', 'mygroup2' ]
#     admin: true
#
# The usernames are given by a list and the groupname is set. The variable
# 'admin' defines if the group has sudoers rights.
#

- name: Include create_user.yml
  ansible.builtin.include_tasks: create_user.yml
  loop: "{{ users | flatten(levels=1) }}"
  loop_control:
    loop_var: user_item
- name: Include create_sudoers.yml
  ansible.builtin.import_tasks: create_sudoers.yml
