---
- name: Converge
  hosts: all
  tasks:
    - name: "Deploy admin user sysadmin in sysadmin group"
      ansible.builtin.include_role:
        name: jkirk.user
      vars:
        users: ["sysadmin"]
        groupname: "admin"
        admin: True
