---
- name: Converge
  hosts: all
  tasks:
    - name: "Deploy admin user sysadmin in sysadmin group"
      ansible.builtin.include_role:
        name: "ansible-role-user"
      vars:
        users: [ 'sysadmin' ]
        groupname: 'admin'
        admin: True
    - name: "Deploy admin user sysadmin in sysadmin group + additional groups 'adm' + 'mygroup1'"
      ansible.builtin.include_role:
        name: "ansible-role-user"
      vars:
        users: [ 'sysadmin' ]
        groupname: 'admin'
        user_groups: [ 'adm', 'mygroup1' ]
        admin: True
