---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: debian_10
    image: debian:buster
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
