---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: debian10
    image: geerlingguy/docker-debian10-ansible
    pre_build_image: true
  - name: debian11
    image: geerlingguy/docker-debian11-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
